---
title: "R Programming Midterm Result : Scores"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

<!--
### Data 
-->

<!--### Excel 자료 읽어들이기 

* excel 파일을 잘 읽어들이는 `xlsx` 패키지를 올려놓고, 자료구조에 맞춰 argument 설정.
    * Sheet 번호, startRow, colIndex, header 의 용도 파악. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xlsx)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
# panderOptions('digits', 3)
```


```{r, read data, echo = FALSE, results = 'hide'}
midterm_roll01 <- read.xlsx("../data/midterm1901_01.xlsx", 
                          sheetIndex = 1, 
                          startRow = 3, 
                          endRow  = 41, 
                          colIndex = c(4, 10:49), 
                          colClasses = rep("character", 41), 
                          encoding = "UTF-8",
                          header = FALSE, 
                          stringsAsFactors = FALSE)
midterm_roll02 <- read.xlsx("../data/midterm1901_02.xlsx", 
                          sheetIndex = 1, 
                          startRow = 3, 
                          endRow  = 41, 
                          colIndex = c(4, 10:49), 
                          colClasses = rep("character", 41), 
                          encoding = "UTF-8",
                          header = FALSE, 
                          stringsAsFactors = FALSE)
names(midterm_roll01) <- c("id", paste("Q", 1:40, sep = ""))
names(midterm_roll02) <- c("id", paste("Q", 1:40, sep = ""))
midterm_roll01$group <- "01"
midterm_roll02$group <- "02"
midterm_roll <- rbind(midterm_roll01, midterm_roll02)
names(midterm_roll) <- c("id", paste0("Q", 1:40), "group")
head(midterm_roll$id)
str(midterm_roll)
kable(midterm_roll)
#>문해력 집계에 필요한 변수만 추출 (id 는 불필요)
midterm <- midterm_roll[, c(2:42)] #> 문해력 집계에 필요한 변수만 추출. 
kable(midterm)
```


## `factor` 변환


```{r, echo = FALSE, eval = TRUE, results = "hide"}
midterm_df <- midterm[1:40] %>%
  lapply(FUN = factor, levels = 1:4, 
         labels = c("가", "나", "다", "라")) %>%
  data.frame(row.names = NULL)
str(midterm_df)
```

# Barplot

막대그래프로 답안 분포를 시각적으로 살핀다. 차후 나오는 정답률과 함께 어느 문항에서 어느 답안을 많이 고르는지 파악하는 데 활용한다.

```{r, echo = FALSE, fig.width = 9, fig.height = 12}
library(RColorBrewer)
par(family = "", mar = c(5.1, 4.1, 4.1, 8.1))
midterm_tbl <- midterm_df %>%
  sapply(FUN = table, useNA = "no")
kable(midterm_tbl[, 1:20], caption = "Counts")
kable(midterm_tbl[, 21:40], caption = "Counts")
midterm_ptbl <- midterm_tbl %>%
  apply(MARGIN = 2, FUN = prop.table) %>%
  `*`(100) %>%
  round(digits = 0)
kable(midterm_ptbl[, 1:20], caption = "%")
kable(midterm_ptbl[, 21:40], caption = "%")
label_ptbl <- midterm_ptbl %>%
  format(digits = 2, nsmall = 0) %>%
  paste0("%") %>%
  ifelse(. %in% c("  0%", "  1%", "  2%"), "", .) %>%
  matrix(nrow = 4)
b <- barplot(matrix(midterm_tbl, nrow = 4), 
             horiz = TRUE, 
             axes = FALSE, 
#              col = rainbow(4), 
             col = brewer.pal(4, "Accent"),
             names.arg = colnames(midterm_tbl), 
             las = 1, 
             xpd = TRUE, 
             legend.text = rownames(midterm_tbl), 
             args.legend = list(x = 90, y = 45))
# max(b)
#midterm_tbl[1, ]
text(x = midterm_tbl[1, ] / 2, 
     y = b, 
     labels = label_ptbl[1, ])
text(x = midterm_tbl[1, ] + midterm_tbl[2, ] / 2, 
     y = b, 
     labels = label_ptbl[2, ])
text(x = midterm_tbl[1, ] + midterm_tbl[2, ] + midterm_tbl[3, ] / 2, 
     y = b, 
     labels = label_ptbl[3, ])
text(x = midterm_tbl[1, ] + midterm_tbl[2, ] + midterm_tbl[3, ] + midterm_tbl[4, ]/ 2, 
     y = b, 
     labels = label_ptbl[4, ])
```

# 점수 계산

* 정답 맞춰보기
    * 정답 읽어들이기. `what = ""`로 설정하여 `char`취급. 

* 각 학생들의 답안과 맞춰보기 위하여 정답표 작성.
    * 문항별로 정답과 비교하기 위하여 각 문항을 리스트의 원소로 분리
    * `split()` 의 기능과 한계에 유의. `factor` 성격으로부터 `1, 10, 11, ..., 2, 20, ..., 3, 4, 5, ... , 9`로 순서를 잡게 되므로 다시 한번 정리할 필요.
    
    
```{r, ans list and unlist, echo = FALSE, results = 'hide'}
ans <- "../data/midterm_ans.txt" %>%
  scan(what = "") %>%
  split(f = paste0("A", 1:40)) %>%
  `[`(paste0("A", 1:40))
ans
```

## 정답과 대조하여 R(Right)/W(Wrong) 표시 
    
* 채점표라는 의미의 `marks` 로 저장, (# 표시한 방식으로는 작동하지 않음)
-->
    
```{r, marks, echo = FALSE}
marks_rw <- midterm_df %>%
  `==`(ans) %>%
  ifelse("R", "W") 
marks_rw[, 1:20] %>%
#  head %>%
  cbind("학번" = midterm_roll$id[1:39], .) %>%
  pander
marks_rw[, 21:40] %>%
#  head %>%
  cbind("학번" = midterm_roll$id[40:78], .) %>%
  pander
```

## 학생별 점수 산출

<!--+ 정답을 집계하기 위하여 "R" 갯수를 다시 산출하는 `ifelse()` 적용.
    + 4점씩 곱하면 100점 만점 기준의 점수가 됨. 
    + 조사표는 작성해서 제출했지만 빈칸이 있는 경우는 그 문항을 0점 처리, 결석의 경우는 점수가 모두 0으로 나오는 경우를  NA처리 
-->

```{r, sum of rights answers, echo = FALSE, results = 'hide'}
marks <- marks_rw %>%
  `==`("R") %>%
  ifelse(1, 0)
score <- marks %>%
  apply(MARGIN = 1, FUN = sum, na.rm = TRUE) %>%
  `*`(2.5)
score[score == 0] <- NA
which(score <= 60)
```

```{r, pander score, echo = FALSE}
score %>%
  format(nsmall = 1) %>%
  cbind("분반" = midterm$group, "학번" = midterm_roll$id, "점수" = .) %>%
  kable(align = c("r", "r"))
```
